Add pkg-config requirement for Debian/derivatives
This is to fix the following error:

Exception: pkg-config binary is required to compile libvirt-python